// flow-typed signature: b48440491badf66d3e3662250c51bdf2
// flow-typed version: <<STUB>>/react-async-component_v2.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-async-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-async-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-async-component/dist/react-async-component' {
  declare module.exports: any;
}

declare module 'react-async-component/dist/react-async-component.min' {
  declare module.exports: any;
}

declare module 'react-async-component/rollup-min.config' {
  declare module.exports: any;
}

declare module 'react-async-component/rollup.config' {
  declare module.exports: any;
}

declare module 'react-async-component/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-async-component/dist/react-async-component.js' {
  declare module.exports: $Exports<'react-async-component/dist/react-async-component'>;
}
declare module 'react-async-component/dist/react-async-component.min.js' {
  declare module.exports: $Exports<'react-async-component/dist/react-async-component.min'>;
}
declare module 'react-async-component/rollup-min.config.js' {
  declare module.exports: $Exports<'react-async-component/rollup-min.config'>;
}
declare module 'react-async-component/rollup.config.js' {
  declare module.exports: $Exports<'react-async-component/rollup.config'>;
}
declare module 'react-async-component/wallaby.js' {
  declare module.exports: $Exports<'react-async-component/wallaby'>;
}
